### ISSUE TITLE
Send Image (WebSocket) not working as expected

### ISSUE THREAD

**Issue by lllleow** [Acly/comfyui-tooling-nodes#1]
First of all I'd like to thank you for this! 
I am having problem with receiving the images via WebSocket with the Send Image node. The images are not being sent.

I am using the same client id in the /prompt request and the WebSocket connection so this should not be the issue.
The last message that I receive is:

`{"type": "status", "data": {"status": {"exec_info": {"queue_remaining": 0}}}}`

And nothing else.
Thanks!

**Comment by lllleow** [comment]
My bad, I was not handling the binary message as I should. Its working as expected now!

**Comment by yty** [comment]
> My bad, I was not handling the binary message as I should. Its working as expected now!

I have this problem as well. Could you share your experience and an example?
