### ISSUE TITLE
hunyuan_dit not detected

### ISSUE THREAD

**Issue by dseditor** [Acly/comfyui-tooling-nodes#17]
},
    "hunyuan_dit_comfyui\\_1.2.safetensors": {
        "base_model": "unknown",
        "error": "Failed to detect base model: argument of type 'NoneType' is not iterable"
    },

the model is from [here](https://huggingface.co/comfyanonymous/hunyuan_dit_comfyui/blob/main/hunyuan_dit_1.2.safetensors)
Can't detect from API

**Comment by Acly** [comment]
Should work now
