### ISSUE TITLE
Incorrect padding 

### ISSUE THREAD

**Issue by twitset** [Acly/comfyui-tooling-nodes#3]
When pasting a base64 encoded image into the textbox, this error message occurs

![image](https://github.com/Acly/comfyui-tooling-nodes/assets/106013863/a527d2ca-e353-4b20-806b-380c1695c703)

**Comment by Acly** [comment]
Please provide the full base64 string (as text) so I can check.

**Comment by twitset** [comment]
[bad_b64.txt](https://github.com/Acly/comfyui-tooling-nodes/files/13300339/bad_b64.txt)

**Comment by twitset** [comment]
It also says that the image file is truncated with this:
[trunc.txt](https://github.com/Acly/comfyui-tooling-nodes/files/13300475/trunc.txt)

**Comment by Acly** [comment]
Seems to be a UI issue. Both b64 strings work fine if I send them directly as part of a prompt.

You can inspect the POST request which is sent by the UI to the server in the browser, and observe the b64 string is truncated there. I think in both cases it is cut off at the first occurence of `//`.

I don't think this can be solved without modifying the front-end/UI. There are probably better ways to solve whatever you're trying to do. The node is geared towards other tools/front-ends which send a prompt via POST directly, where this issue doesn't occur.

**Comment by 42lux** [comment]
I had the same problem with my base64 nodes disable multiline and you are fine.

**Comment by Acly** [comment]
That works, thanks!
