### ISSUE TITLE
TypeError: theirNode.widgets is undefined

### ISSUE THREAD

**Issue by Eggwardhan** [Acly/comfyui-tooling-nodes#30]
Loading aborted due to error reloading workflow data

TypeError: theirNode.widgets is undefined

adaptWidgetsToConnection@http://127.0.0.1:8188/extensions/comfyui-tooling-nodes/external_tooling_nodes.js:152:29
setupParameterNode/nodeType.prototype.onAfterGraphConfigured@http://127.0.0.1:8188/extensions/comfyui-tooling-nodes/external_tooling_nodes.js:173:33
#addAfterConfigureHandler/app2.graph.onConfigure@http://127.0.0.1:8188/assets/index-BHayQCxv.js:78088:15
configure@http://127.0.0.1:8188/assets/index-BHayQCxv.js:69322:10
#addConfigureHandler/LGraph.prototype.configure@http://127.0.0.1:8188/assets/index-BHayQCxv.js:78040:26
init/LGraph.prototype.configure@http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/reroutePrimitive.js:14:29
loadGraphData@http://127.0.0.1:8188/assets/index-BHayQCxv.js:78562:18

This may be due to the following script:
/extensions/comfyui-tooling-nodes/external_tooling_nodes.js

when I try to load JK：：Image Gen SDXL，it raise this error

**Comment by Acly** [comment]
I think this happened when loading a workflow that contains nodes you don't have installed.

Should work after updating to latest version (https://github.com/Acly/comfyui-tooling-nodes/commit/50c3ffdf649bd55a0b985d775e79cfe62bae1379 just now)
