### ISSUE TITLE
HELP!!!!!!!!!!!! SyntaxError: invalid syntax cause comfyui-tooling-nodes Import failed??

### ISSUE THREAD

**Issue by minnieee829** [Acly/comfyui-tooling-nodes#31]
File "/Users/minnie/ComfyUI/custom_nodes/comfyui-tooling-nodes/nodes.py", line 277
    match weight:
          ^
SyntaxError: invalid syntax

Cannot import /Users/minnie/ComfyUI/custom_nodes/comfyui-tooling-nodes module for custom nodes: invalid syntax (nodes.py, line 277)

When I run the server, it shown this error, please help.
Now I can't connect the server on Krita cause it can not import.

**Comment by Acly** [comment]
What Python version are you using?

**Comment by Acly** [comment]
Try updating, should work with older versions now.
