### ISSUE TITLE
SyntaxError: invalid syntax (nodes.py, line 277)

### ISSUE THREAD

**Issue by minnieee829** [Acly/comfyui-tooling-nodes#32]
https://github.com/Acly/comfyui-tooling-nodes/blame/d7d421baaa7d3140fd7fc500d928244045211217/nodes.py#L277C3-L277C3

SyntaxError: invalid syntax  Cannot import /Users/minnie/ComfyUI/custom_nodes/comfyui-tooling-nodes module for custom nodes: invalid syntax (nodes.py, line 277)

**Comment by Acly** [comment]
Should only be a problem for old Python version (3.9 and earlier), but I changed it to be more compatible.
