### ISSUE TITLE
Unable to send images from ComfyUI to Krita.

### ISSUE THREAD

**Issue by huihuihui-wq** [Acly/comfyui-tooling-nodes#33]
![屏幕截图 2024-12-12 001940](https://github.com/user-attachments/assets/2cee0136-f0e7-4112-a243-21cbda98fea1)
However, Krita can generate images on its own.
![Uploading 3333.png…]()

**Comment by Acly** [comment]
Yes that's not how it works, it does not send images. It just marks the outputs for when you run the workflow via Krita.
