### ISSUE TITLE
support for boolen parameter

### ISSUE THREAD

**Issue by zixuzhuang** [Acly/comfyui-tooling-nodes#34]
Hi Acly, your custom nodes are really great! 
It would be nice to add support for boolen type inputs in krita, appreciated.

**Comment by Acly** [comment]
It should work.

![image](https://github.com/user-attachments/assets/34f7c144-ff93-4e9a-800d-c0e906aea62e)

![image](https://github.com/user-attachments/assets/83e89ff0-bc87-4666-9cd0-43a0352f2c41)

**Comment by zixuzhuang** [comment]
Thanks for your reply, it works fine!
