### ISSUE TITLE
Unexpected JSON Output from Send Image (WebSocket) Node

### ISSUE THREAD

**Issue by mkg2145** [Acly/comfyui-tooling-nodes#6]
Hello,

I'm experiencing an issue with the Send Image (WebSocket) node where the output is unexpectedly in JSON format. According to the documentation, I was expecting a binary message followed by PNG data. However, my console debug output indicates the reception of JSON first, as follows: First few bytes of image data: b'{"prompt_i'. and Image data size: 87 bytes

Could you please clarify if this behavior is intentional or if I might be overlooking something in the implementation?

Thank you for your assistance.

**Comment by Acly** [comment]
Hi, the node does send a JSON message like all other nodes, to track progress. The PNG data is separate message on top. Websocket protocol has "text frame" and "binary frame", in case of ComfyUI text usually is JSON and binary is used for images.

**Comment by mkg2145** [comment]
Hello Acly,
Thank you for your quick response.
I've been implementing the Send Image (WebSocket) node as per the documentation, expecting to receive a binary PNG image following an initial JSON message. However, I seem to be encountering an issue where no binary image data is received, only the JSON text frame.

In the debug output, I receive the JSON message, but the subsequent binary message, which should contain the PNG data, doesn't appear to be arriving or is not being correctly identified by the client. The client-side code is set up to handle ArrayBuffer data and has been tested to ensure it processes binary data correctly.

Could you provide some insight or clarification on how the server sends the binary data following the JSON message? Is there a specific event or header that we should listen for to differentiate between the JSON and PNG binary frames? Any additional guidance on handling the sequence of messages would be greatly appreciated.

Thank you for your assistance.
Yuri

**Comment by Acly** [comment]
I don't have code for Javascript, but two things to keep in mind:
* The binary message(s) with the image data come first, the JSON message afterwards
* The binary blob starts with two 32bit integers, the PNG header comes afterwards - you need to strip those away before passing it to an image loader

What output do you actually see, no binary messages at all?

**Comment by mkg2145** [comment]
Hi Acly,

![Screenshot 2023-12-07 232913](https://github.com/Acly/comfyui-tooling-nodes/assets/144164780/461e1fb4-2a43-44c5-98ac-ac41e6ad2dc5)
There's my workflow.

and I am trying to display the output image here:
![image](https://github.com/Acly/comfyui-tooling-nodes/assets/144164780/52512bf1-7ce0-41cf-b8b6-5e5e48a06178)


Thank you for your previous response. I've updated my WebSocket client to prioritize handling binary data and to skip the initial 8 bytes (two 32-bit integers) before processing the PNG data. Despite these adjustments, I'm still not receiving any binary image data, only JSON messages.

I'm trying to generate with comfy the above workflow with code, and display the image in the webrowser.

**Comment by mkg2145** [comment]
Thank you for your responses and this repository. I realized I was trying to read the binary messages with JS and not python. 


I need to establish a WebSocket connection to the ComfyUI server (ws://127.0.0.1:8188/) using Python to receive generated images through WebSocket connection. However, I'm encountering aissue where the server rejects the WebSocket connection with an "HTTP 200" error.

Here's a brief overview of my setup:

Environment: Local server running Comfy on 127.0.0.1:8188.
Language: Python, using the websockets library for the WebSocket client.
Issue: Whenever I try to connect to the WebSocket server, I receive the error "WebSocket error: server rejected WebSocket connection: HTTP 200".
Comfy is running and generates images 
![image](https://github.com/Acly/comfyui-tooling-nodes/assets/144164780/df7a52ab-5c1d-4af2-a123-9aa8990dad9c)

The problem is receiving and displaying the image.

Below is a snippet of the Python code I'm using to establish the WebSocket connection:

```
# WebSocket listener function
async def listen_for_images():
    uri = "ws://127.0.0.1:8188/"  # ComfyUI WebSocket URI
    try:
        async with websockets.connect(uri) as websocket:
            async for msg in websocket:
                if isinstance(msg, bytes):
                    s = struct.calcsize(">II")
                    if len(msg) > s:
                        event, format = struct.unpack_from(">II", msg, 0)
                        if event == 1 and format == 2:  # Preview Image in PNG format
                            image_data = msg[s:]
                            image_base64 = base64.b64encode(image_data).decode('utf-8')
                            socketio.emit('image_data', {'type': 'binary', 'data': image_base64})
    except Exception as e:
        print(f"WebSocket error: {e}")

# Function to start the WebSocket listener in a new thread
def start_websocket_listener():
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    loop.run_until_complete(listen_for_images())
    loop.close()
```

**Comment by Acly** [comment]
You don't have to use Python, I'm sure JS can work too.
Regarding connection reject: maybe it's because `clientId` is missing?

**Comment by mkg2145** [comment]
Yes. I did it through Python because clientID was missing as you suggested. Thank you!

**Comment by mkg2145** [comment]
Closing. Thank you for your assistance.
