### ISSUE TITLE
Question on ComfyUI's "Load Image (Base64)" Node

### ISSUE THREAD

**Issue by mkg2145** [Acly/comfyui-tooling-nodes#7]
Greetings, thank you for your help with the previous problem.

I am able to send one image with Load Image node. valuable for me thank you. 

I'm working on a project where I need to send two images input images with the "Load Image (Base64)" node .

Can this node handle two base64 images at once? 

I'm receiving errors in comfy

```
File "D:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\PIL\Image.py", line 3298, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x00000245B4F40770>

Prompt executed in 0.01 seconds
```

Thank you for your quick responses.

**Comment by Acly** [comment]
No, for two images use two nodes.
